---
sudo: false

language: elixir
elixir:
  - 1.7.2
  - 1.6.6
otp_release:
  - 21.0
  - 20.3

addons:
  apt:
    packages:
    - nodejs
    - libmozjs-24-bin
    - libjavascriptcoregtk-3.0-bin
    - rhino

env:
  - EXECJS_RUNTIME=Node
  - EXECJS_RUNTIME=SpiderMonkey
  - EXECJS_RUNTIME=JavaScriptCore
  - EXECJS_RUNTIME=Rhino
