language: erlang
otp_release:
  - 17.0-rc1
  - R16B03-1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rhino
  - git clone -b v0.12.4 --depth 1 git://github.com/elixir-lang/elixir
  - make -C elixir
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix deps.get
script:
  - mix test
env:
  - EXECJS_RUNTIME=Node
  - EXECJS_RUNTIME=Rhino
