language: elixir
elixir: 1.0.1
otp_release:
  - 17.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rhino
before_script:
  - MIX_ENV=test mix deps.get
script:
  - mix test
env:
  - EXECJS_RUNTIME=Node
  - EXECJS_RUNTIME=Rhino
