language: erlang
otp_release:
  - 17.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rhino
  - wget https://github.com/elixir-lang/elixir/releases/download/v1.0.1/Precompiled.zip
  - unzip -d elixir Precompiled.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - MIX_ENV=test mix deps.get
script:
  - mix test
env:
  - EXECJS_RUNTIME=Node
  - EXECJS_RUNTIME=Rhino
